# Generated by Django 4.0.3 on 2022-03-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
    ]
