# Generated by Django 4.0.3 on 2022-03-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0014_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='static/images/photo_post_template.png', null=True, upload_to='blogspot/images'),
        ),
    ]
