# Generated by Django 4.0.3 on 2022-03-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0015_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/images/photo_post_template.png', upload_to='blogspot/images'),
        ),
    ]
